---
# Elasticsearch 
- name: Install Elasticsearch    
  hosts: elasticsearch
  roles:
    - elastic
  tags: elastic

# Kibana
- name: Install Kibana 
  hosts: kibana
  roles:
    - kibana-role
  tags: kibana

#Filebeat
- name: Install Filebeat
  hosts: app
  roles:
    - filebeat-role
  tags: filebeat
