---
- name: Prepare jenkins agent
  hosts: elasticsearch
  become: true
  become_user: "jenkins"
  tasks:
    - name: Add master publickey into authorized_key
      authorized_key:
        user: "jenkins"
        state: present
        key: "{{ hostvars['el-instance']['ssh_key_info']['ssh_public_key'] }}"
        
# Elasticsearch 
- name: Install Elasticsearch    
  hosts: elasticsearch
  roles:
    - elastic
  tags: elastic

# Kibana
- name: Install Kibana 
  hosts: kibana
  roles:
    - kibana-role
  tags: kibana

#Filebeat
- name: Install Filebeat
  hosts: app
  roles:
    - filebeat-role
  tags: filebeat
